return {
    tracks = {
        {
            title = 'Raining Tacos',
            artist = 'Parry Gripp',

            cover = 80261389452352,
            audioId = 142376088
        },
        {
            title = 'Crab Rave',
            artist = 'Noisestorm',

            audioId = 5410086218
        },
        {
            title = 'Waltz of The Flowers',
            artist = 'Tchaikovsky',
            
            audioId = 1848059313
        }
    }
}